<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hlsl</string>
		<string>fx</string>
	</array>
	<key>name</key>
	<string>HLSL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>test</string>
			<key>match</key>
			<string>\b((float|float[1234])|(half|half[1234])|(int|int[1234])|(uint|uint[1234])|(double|double[1234])|(bool|bool[1234])|(float[1-4]x[1-4])|(int[1-4]x[1-4])|(half[1-4]x[1-4])|(double[1-4]x[1-4])|([Tt]exture|[Tt]exture(1D|2D|3D|Cube|CUBE))|(sampler|sampler(1D|2D|3D|CUBE))|void)\b</string>
			<key>name</key>
			<string>storage.type.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>\b(unorm|const|static|extern|register)\b</string>
			<key>name</key>
			<string>storage.modifier.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>\b(break|case|continue|default|do|else|for|goto|if|_Pragma|return|switch|while)\b</string>
			<key>name</key>
			<string>keyword.control.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>\b(abs|ceil|clamp|cross|degrees|determinant|distance|dot|floor|length|lerp|log|log10|log2|max|min|mul|normalize|pow|radians|reflect|refract|rsqrt|saturate|sin|sincos|sqrt|tan|transpose)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.source.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.hlsl</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>test2</string>
			<key>match</key>
			<string>/\*.*\*/</string>
			<key>name</key>
			<string>comment.hlsl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hlsl</string>
	<key>uuid</key>
	<string>f42f5931-4574-438e-a6f8-b406cade4616</string>
</dict>
</plist>
